public class tugas13{
    public static void main(String[] args) {
        Scanner input = new Scanner (System.in);
        boolean a = false;
        boolean b = true;
        boolean c = false;
        boolean d = true;

        System.out.println("Berikut ini manakah yang termasuk jenis operator di dalam pemrograman Java");
        System.out.println("Pilihan jawabannya adalah\t:");
        System.out.println("A. ");
        System.out.println();
        System.out.println();
        System.out.println();
    }    
}